In [1]:
import numpy as np

In [13]:
myArr = np.array([[3,4,5,6,67,89]])

In [14]:
myArr

array([[ 3,  4,  5,  6, 67, 89]])

In [15]:
print(myArr[0,4])

67


In [16]:
myArr.shape


(1, 6)

In [17]:
myArr.dtype


dtype('int32')

### Array Creation : from other python structures


In [18]:
arr = np.array([[3,4,5],[1,7,9]])
arr

array([[3, 4, 5],
       [1, 7, 9]])

### intrinsic method

In [19]:
zeros = np.zeros((2,7))

In [20]:
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
zeros.shape

(2, 7)

In [23]:
zeros.size

14

In [24]:
range = np.arange(15)

In [25]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
lspace = np.linspace(10,40,40)

In [30]:
lspace

array([10.        , 10.76923077, 11.53846154, 12.30769231, 13.07692308,
       13.84615385, 14.61538462, 15.38461538, 16.15384615, 16.92307692,
       17.69230769, 18.46153846, 19.23076923, 20.        , 20.76923077,
       21.53846154, 22.30769231, 23.07692308, 23.84615385, 24.61538462,
       25.38461538, 26.15384615, 26.92307692, 27.69230769, 28.46153846,
       29.23076923, 30.        , 30.76923077, 31.53846154, 32.30769231,
       33.07692308, 33.84615385, 34.61538462, 35.38461538, 36.15384615,
       36.92307692, 37.69230769, 38.46153846, 39.23076923, 40.        ])

In [35]:
emp = np.empty((2,5))

In [36]:
emp


array([[10.        , 13.33333333, 16.66666667, 20.        , 23.33333333],
       [26.66666667, 30.        , 33.33333333, 36.66666667, 40.        ]])

In [37]:
emp_like = np.empty_like(lspace)

In [38]:
emp_like

array([10.        , 10.76923077, 11.53846154, 12.30769231, 13.07692308,
       13.84615385, 14.61538462, 15.38461538, 16.15384615, 16.92307692,
       17.69230769, 18.46153846, 19.23076923, 20.        , 20.76923077,
       21.53846154, 22.30769231, 23.07692308, 23.84615385, 24.61538462,
       25.38461538, 26.15384615, 26.92307692, 27.69230769, 28.46153846,
       29.23076923, 30.        , 30.76923077, 31.53846154, 32.30769231,
       33.07692308, 33.84615385, 34.61538462, 35.38461538, 36.15384615,
       36.92307692, 37.69230769, 38.46153846, 39.23076923, 40.        ])

In [39]:
ide = np.identity(3)

In [40]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
ide.dtype

dtype('float64')

In [49]:
arr = np.arange(99)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [51]:
arr = arr.reshape(3,33)

In [52]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [53]:
arr.shape

(3, 33)

In [54]:
arr = arr.ravel()

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [56]:
arr.shape

(99,)

In [57]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [66]:
ar = np.array(x)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
ar.sum(axis=0)

array([12, 15, 18])

In [69]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [70]:
ar[2,2]

9

#### Transpose of an array


In [71]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
ar.flat

In [75]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [76]:
ar.ndim

2

### total bytes consumed by array

In [77]:
ar.nbytes

36

## Methods

In [78]:
one = np.array([1,3,6,8,45,90,3,23])

In [79]:
one.argmax()

5

In [82]:
one.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [83]:
one.argmin()

0

In [90]:
y = [[10,5,3],[44,9,34],[7,87,1]]

In [91]:
arr2 = np.array(y)

In [92]:
arr2

array([[10,  5,  3],
       [44,  9, 34],
       [ 7, 87,  1]])

In [93]:
arr2.argmax()

7

In [94]:
arr2.argmin()

8

In [95]:
arr2.argsort()

array([[2, 1, 0],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

In [96]:
arr2.argsort(axis=0)

array([[2, 0, 2],
       [0, 1, 0],
       [1, 2, 1]], dtype=int64)

In [97]:
arr2.argsort(axis=1)

array([[2, 1, 0],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

In [98]:
arr2.ravel()

array([10,  5,  3, 44,  9, 34,  7, 87,  1])

In [99]:
arr2.reshape(1,9)

array([[10,  5,  3, 44,  9, 34,  7, 87,  1]])

In [101]:
arr3 = np.array([[3,1,2],[4,0,3],[1,6,2]])

In [102]:
arr3

array([[3, 1, 2],
       [4, 0, 3],
       [1, 6, 2]])

In [103]:
arr4 = np.array([[3, 0, 4],
       [4, 1, 2],
       [1, 8, 1]])

In [104]:
arr4

array([[3, 0, 4],
       [4, 1, 2],
       [1, 8, 1]])

In [106]:
arr3+arr4

array([[ 6,  1,  6],
       [ 8,  1,  5],
       [ 2, 14,  3]])

In [107]:
arr3*arr4

array([[ 9,  0,  8],
       [16,  0,  6],
       [ 1, 48,  2]])

In [108]:
arr3/arr4

C:\Users\Prashant\AppData\Local\Temp\ipykernel_1960\2275417534.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/arr4


array([[1.  ,  inf, 0.5 ],
       [1.  , 0.  , 1.5 ],
       [1.  , 0.75, 2.  ]])

In [109]:
arr3-arr4

array([[ 0,  1, -2],
       [ 0, -1,  1],
       [ 0, -2,  1]])

In [110]:
arr3**arr4

array([[     27,       1,      16],
       [    256,       0,       9],
       [      1, 1679616,       2]])

In [111]:
np.sqrt(arr3)

array([[1.73205081, 1.        , 1.41421356],
       [2.        , 0.        , 1.73205081],
       [1.        , 2.44948974, 1.41421356]])

In [112]:
arr3.sum()

22

In [113]:
arr4.min()

0

In [116]:
arr3

array([[3, 1, 2],
       [4, 0, 3],
       [1, 6, 2]])

In [118]:
arr3.shape

(3, 3)

In [120]:
np.where(arr3 > 2)

(array([0, 1, 1, 2], dtype=int64), array([0, 0, 2, 1], dtype=int64))

In [124]:
np.count_nonzero(arr3)

8

In [126]:
np.nonzero(arr4)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [127]:
import sys

In [128]:
py_ar = [1,2,3,4]

In [129]:
np_ar = np.array(py_ar)

In [137]:
sys.getsizeof(1) * len(py_ar)

112

In [134]:
np_ar.itemsize * np_ar.size

16